### ISSUE TITLE
Errors in windowed and fullscreen 

### ISSUE THREAD

**Issue by eyenalxai** [gtw123/OpusSolver#1]
I have single display (laptop).
In fullscreen bot thinks that something is overlapping game window.
In windowed bot finds game window, but struggles to find "pallette headers".

[Opus.log](https://github.com/gtw123/OpusSolver/files/2088072/Opus.log)

**Comment by gtw123** [comment]
Interesting - I'll probably have to add some more logging to help figure out what's going on.

**Comment by eyenalxai** [comment]
Fixed errors by disabling FPS counter in Steam settings. Got new errors.
[Opus - Copy.log](https://github.com/gtw123/OpusSolver/files/2088910/Opus.-.Copy.log)

**Comment by gtw123** [comment]
I've added some extra logging when it searches for overlapping windows. (It tries to check there are no overlapping windows before starting, because otherwise the keyboard/mouse input might go to a different application on your computer and do bad things!)

For your new errors, it looks like it's still having problems analyzing the sidebar. If you edit Opus/App.Config and set ```ScreenCapture.LoggingEnabled``` to ```true```, then try running it again, it will save screenshots as it analyzes the screen. You could then attach them to this issue (with a new log file). That should hopefully let us see why it's having problems!

**Comment by eyenalxai** [comment]
Here
Screenshots take a lot of space, so I'm sending them as .zip
[screenshots.zip](https://github.com/gtw123/OpusSolver/files/2092708/screenshots.zip)
[Opus.log](https://github.com/gtw123/OpusSolver/files/2092699/Opus.log)

**Comment by gtw123** [comment]
Thanks. That's really strange - if you look at the first screenshot you can see it's chopping off the bottom and right edges of the window:
![0](https://user-images.githubusercontent.com/39769164/41292911-68b532a8-6e86-11e8-87b6-af8aa68e843f.png)

It's supposed to look like this:
![0](https://user-images.githubusercontent.com/39769164/41293200-3e66fca6-6e87-11e8-9a29-1f1966bbb8b1.png)

I've added even more logging now. Could you pull or download the latest version, try running it again, then attach the new log file again? Hopefully that'll let us see where the problem is coming from.

**Comment by eyenalxai** [comment]
Turns out cropping problems were caused by interface scaling in Windows. It was at 125%, I totally forgot that I'm using it. 
This time bot placed some elements, but something else went wrong again.
A lot of screenshots, using Dropbox.
https://www.dropbox.com/s/cqxwb6aimgjwgym/screenshots__2.zip?dl=0
[Opus.log](https://github.com/gtw123/OpusSolver/files/2094643/Opus.log)

**Comment by gtw123** [comment]
Nice catch! I think I can probably make it more tolerant of interface scaling in the future...

In the meantime it looks like it's sometimes failing to right-drag with the mouse. This could be because it's doing it too quickly. I could probably try to make this a lot more robust, but for now I've added another setting that might help. Can you please:
* Pull from master (or download the latest version)
* Edit App.config and set ```MouseUtils.GlobalDragDelay``` to 50, and ```ScreenCapture.LoggingEnabled``` to true again.
* Build and run.

If that doesn't help, try increasing the delay to 200. If that works, then we'll know the problem was a timing issue!

**Comment by eyenalxai** [comment]
Works perfectly at 30! Thanks a lot! Watching how bot solves levels is completely mesmerizing!

**Comment by gtw123** [comment]
Glad to hear it's working now! :)

I've just added a change which I think will make it work properly with interface scaling in Windows.

If the timing issue is a problem for a lot of people I could the drag delay setting it to the UI or (ideally) make the solver try to calibrate automatically. But for now I'll take the easy approach of just documenting it in the readme :)
